DROP TABLE IF EXISTS `game_log`;
CREATE TABLE `game_log` (
  `serv_id` tinyint unsigned NOT NULL DEFAULT '0',
  `act_time` int unsigned NOT NULL DEFAULT '0',
  `log_id` SMALLINT unsigned NOT NULL DEFAULT '0',
  `actor` int unsigned NOT NULL DEFAULT '0',
  `actor_type` VARCHAR(75) NOT NULL DEFAULT '',
  `target` int unsigned NOT NULL DEFAULT '0',
  `target_type` VARCHAR(75) NOT NULL DEFAULT '0',
  `location_x` MEDIUMINT,
  `location_y` MEDIUMINT,
  `location_z` SMALLINT,
  `etc_str1` VARCHAR(50),
  `etc_str2` VARCHAR(50),
  `etc_str3` VARCHAR(50),
  `etc_num1` int NOT NULL DEFAULT '0',
  `etc_num2` int NOT NULL DEFAULT '0',
  `etc_num3` int NOT NULL DEFAULT '0',
  `etc_num4` int NOT NULL DEFAULT '0',
  `etc_num5` int NOT NULL DEFAULT '0',
  `etc_num6` int NOT NULL DEFAULT '0',
  `etc_num7` int NOT NULL DEFAULT '0',
  `etc_num8` int NOT NULL DEFAULT '0',
  `etc_num9` BIGINT NOT NULL DEFAULT '0',
  `etc_num10` BIGINT NOT NULL DEFAULT '0',
  `STR_actor` VARCHAR(2000),
  `STR_actor_account` VARCHAR(2000),
  `STR_target` VARCHAR(2000),
  `STR_target_account` VARCHAR(2000),
  `item_id` int unsigned
) ENGINE=ARCHIVE DEFAULT CHARSET=utf8;